apiVersion: v1
kind: Secret
metadata:
  name: market-secret
  namespace: market
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASS: postgres
  JWT_SECRET: your-super-secret-key
  RABBITMQ_USER: guest
  RABBITMQ_PASS: guest
